FROM debian:stretch

# Conda stuffs
RUN apt-get -qq update && apt-get -qq -y install curl bzip2 \
    && curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -bfp /usr/local \
    && rm -rf /tmp/miniconda.sh \
    && conda install -y python=3 \
    && conda update conda \
    && apt-get -qq -y remove curl bzip2 \
    && apt-get -qq -y autoremove \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* /var/log/dpkg.log \
    && conda clean --all --yes

ENV PATH /opt/conda/bin:$PATH

# Install jupyterlab
RUN conda install -c conda-forge jupyterlab nodejs 

# Run Jupyter
EXPOSE 8888
RUN mkdir -p /opt/app/data
CMD jupyter lab --ip=0.0.0.0 --port=8888 --notebook-dir=/opt/app/data --allow-root
